name: TFX

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test-tfx-deployer:
    # Name the Job
    name: Train/Deploy/Test TFX - Locally
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Build, Train, Deploy, Predict, Destroy TFX
      - name: Test mnist TFX
        run: |
          make train-mnist-tf
          make deploy-mnist-tfx
          sleep 5
          make predict-mnist-tfx
          make destroy-mnist-tfx
